### ISSUE TITLE
How to add comma instead of spaces?

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Kocal/vue-numerals#145] opened 2019-04-04 16:59 UTC
This - `1000 `==> change to this `1 000`

But i want this result:
`1,000`

Thanks.

**Comment by Kocal** [comment] 2019-04-04 19:44
Hi,

You can take a look to available formats here: http://numeraljs.com/#format

I think you should use `0,0` format.

**Comment by Ezra-Siton-UIX** [comment] 2019-04-06 20:15
Not working well. The code added space instead of comma

**Comment by Kocal** [comment] 2019-04-07 05:36
Maybe you should configure a locale?

**Comment by Kocal** [comment] 2019-04-07 05:45
Okay, so the issue is because the default locale is `fr`: https://github.com/Kocal/vue-numerals/blob/master/src/index.js#L9

As you can see there is a test with locale `en` and the default format (`0,0`), and it gives the output you want: https://github.com/Kocal/vue-numerals/blob/master/test/index.test.js#L31-L37

Maybe I should document this behavior.

**Comment by Kocal** [comment] 2019-04-07 06:16
I'm closing since the issue is coming from the default locale.
I've released [v3.0.0](https://github.com/Kocal/vue-numerals/releases/tag/v3.0.0).

**Closed by Kocal** 2019-04-07 06:16 UTC

**Comment by Ezra-Siton-UIX** [comment] 2019-04-07 09:11
Thanks! now works fine :)
