### ISSUE TITLE
L10n - PT BR

### ISSUE THREAD

**Issue by allpereira** [Kocal/vue-numerals#8] opened 2018-06-26 16:49 UTC
Hi! 

I'm trying to use Brazil localization such as below:
`Vue.use(VueNumerals, {locale: 'pt-br'});`

But the following erros is throw: "TypeError: Cannot read property 'delimiters' of undefined"

**Comment by allpereira** [comment] 2018-07-03 12:44
?????

**Comment by hmaesta** [comment] 2018-11-16 11:29
Did you find a solution?
Several [locales from Numerals.js](https://github.com/adamwdraper/Numeral-js/tree/master/locales) doesn't work – and I can't think why.

✅ Locales working: `en, bg, cs, de-ch, de, en-au, en-gb, en-za, es-es, es, et, fi, fr-ca, fr-ch, fr, hu, it, ja, lv, no, pl, ru-ua, ru, sk, sl, th, tr, vi`
🚫 Locales not working: `chs, da-dk, nl-be, nl-nl, pt-br, pt-pt, uk-ua`

@Kocal Help needed.

**Comment by Kocal** [comment] 2018-11-16 14:07
Sorry for not having reply to your issue earlier, this repo was marked as `Not watching` (I don't know why) and I wasn't notified at all before you @ me. 
To be honest I though I was the only one to use this package... :sweat_smile: 

I was able to reproduce the issue, I'm working on it.

**Closed** 2018-11-16 14:39 UTC

**Comment by Kocal** [comment] 2018-11-16 14:58
I released v1.0.1, can you try if it's working fine for you @allpereira / @hmaesta?

**Comment by Kocal** [comment] 2018-11-16 18:53
Oh, I forgot to remove [this code](https://github.com/Kocal/vue-numerals/blob/178daa4a4cdb3856b9f9cbbff8ba080dcfbcd723/src/index.js#L11-L17) in https://github.com/Kocal/vue-numerals/pull/12 (introduced in https://github.com/Kocal/vue-numerals/pull/11).

Since I'm french and my browser too, `navigator.language` returns me `fr-FR` and this locale doesn't exist in Numerals, this is why I wanted to transform `x-X` to `x` but... I will remove it. New patch will be available soon

**Comment by Kocal** [comment] 2018-11-16 21:17
Released in 1.1.0
